# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-commit-later" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "b31a3b4f72baa72f1b4d0ea119f90da96e4ef5030d5e66fe990a1e8eba4b2a68"
      url "https://github.com/vaske/git-commit-later/releases/download/v#{version}/git-commit-later_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e2ed3eeceb2118cb0dfb7174ccbffebb76c656a1d5a293af923ab3ac133c7e6e"
      url "https://github.com/vaske/git-commit-later/releases/download/v#{version}/git-commit-later_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "781311495cf2ae67abf8fdc0d1fbc2693f16ad47815e51f74399c6899ab7baef"
      url "https://github.com/vaske/git-commit-later/releases/download/v#{version}/git-commit-later_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "19105f1d1ff284a34152130a8d791d7a9acfc8a50613939b668f5c6290094b33"
      url "https://github.com/vaske/git-commit-later/releases/download/v#{version}/git-commit-later_linux_amd64.tar.gz"
    end
  end

  name "git-commit-later"
  desc "Schedule a staged Git commit for later"
  homepage "https://github.com/vaske/git-commit-later"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-commit-later"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-commit-later"]
    end
  end

  # No zap stanza required
end
